import Head from "next/head";
import { Main } from "../src/components/Main";
// import { InterestFormButton } from "../src/components/ui/InterestFormButton";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Luminos Energi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main />
        {/* <InterestFormButton /> */}
      </main>
    </div>
  );
}
