import Head from "next/head";
import React from "react";
import { InterestFormMain } from "../src/components/InterestFormMain";

const intresseanmalan = () => {
  return (
    <div>
      <Head>
        <title>Luminos Energi | Intresseanmälan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InterestFormMain />
    </div>
  );
};

export default intresseanmalan;
