import Head from "next/head";
import React from "react";
import { ContactMain } from "../src/components/ContactMain";
import { InterestFormButton } from "../src/components/ui/InterestFormButton";

const kontakt = () => {
  return (
    <div>
      <Head>
        <title>Luminos Energi | Kontakt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactMain />
      <InterestFormButton />
    </div>
  );
};

export default kontakt;
