import Head from "next/head";
import React from "react";
import { AboutMain } from "../src/components/AboutMain";
import { InterestFormButton } from "../src/components/ui/InterestFormButton";

const omLuminos = () => {
  return (
    <div>
      <Head>
        <title>Luminos Energi | Om Luminos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutMain />
      <InterestFormButton />
    </div>
  );
};

export default omLuminos;
