import Head from "next/head";
import React from "react";
import { InterestFormButton } from "../src/components/ui/InterestFormButton";
import { SolarCellsMain } from "../src/components/SolarCellsMain";

const varforSolceller = () => {
  return (
    <div>
      <Head>
        <title>Luminos Energi | Varför Solceller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SolarCellsMain />
      <InterestFormButton />
    </div>
  );
};

export default varforSolceller;
